# TODO: make the check flexible
- name: Check if Slurm packages already exist in cluster share
  stat:
    path: "/opt/cluster_share/slurm-smd_25.11.4-1_amd64.deb"
  register: slurm_deb

- name: Set rebuild flag
  set_fact:
    needs_build: "{{ not slurm_deb.stat.exists }}"

- name: Install Debian packaging tools
  become: true
  apt:
    name: [lbzip2, build-essential, fakeroot, devscripts, equivs]
    state: present
  when: needs_build

- name: Clean & Recreate build workspace
  become: true
  file:
    path: "/opt/slurm_build"
    state: "{{ item }}"
    owner: "ansible_svc"
    group: "ansible_svc"
    mode: '0755'
  loop: [absent, directory]
  when: needs_build

- name: Create specific src directory
  file:
    path: /opt/slurm_build/src
    state: directory
  when: needs_build

- name: Download and Unpack Slurm source
  become: yes
  unarchive:
    src: "https://download.schedmd.com/slurm/slurm-25.11-latest.tar.bz2"
    dest: /opt/slurm_build/src
    remote_src: yes
    extra_opts: ['--strip-components=1']
    owner: "ansible_svc"
    group: "ansible_svc"
  when: needs_build

- name: Install dependencies (mk-build-deps)
  become: true
  shell: |
    mk-build-deps -i debian/control -t "apt-get -y -o Debug::pkgProblemResolver=yes --no-install-recommends"
  args:
    chdir: /opt/slurm_build/src
  when: needs_build

- name: Build Slurm packages (this could take a while ...)
  shell: debuild -b -uc -us
  args:
    chdir: /opt/slurm_build/src
  register: build_output
  async: 3600
  poll: 30
  when: needs_build

- name: create clustron share folder
  become: true
  file:
    path: "/opt/cluster_share"
    state: "directory"
    owner: "ansible_svc"
    group: "ansible_svc"
    mode: '0755'
  when: needs_build

- name: Move generated deb files to shared folder
  shell: mv /opt/slurm_build/*.deb /opt/cluster_share/
  become: true
  when: needs_build
