// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package jwt

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	IsActive       pgtype.Bool
	ExpirationDate pgtype.Timestamptz
}

type User struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Role       pgtype.Text
	Department pgtype.Text
	StudentID  pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
