// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CasbinEnforcer is an autogenerated mock type for the CasbinEnforcer type
type CasbinEnforcer struct {
	mock.Mock
}

// Enforce provides a mock function with given fields: role, path, method
func (_m *CasbinEnforcer) Enforce(role string, path string, method string) (bool, error) {
	ret := _m.Called(role, path, method)

	if len(ret) == 0 {
		panic("no return value specified for Enforce")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (bool, error)); ok {
		return rf(role, path, method)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(role, path, method)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(role, path, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCasbinEnforcer creates a new instance of CasbinEnforcer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCasbinEnforcer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CasbinEnforcer {
	mock := &CasbinEnforcer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
