- name: Restart Slurmdbd
  become: true
  service:
    name: slurmdbd
    state: restarted

- name: Restart Slurmctld
  become: true
  service:
    name: slurmctld
    state: restarted

- name: Reconfigure Slurm
  become: yes
  systemd:
    name: slurmctld
    state: restarted
    daemon_reload: yes
