// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package setting

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PublicKey struct {
	UserID    uuid.UUID
	Keyname   string
	PublicKey string
}

type Setting struct {
	UserID        uuid.UUID
	Username      string
	LinuxUsername pgtype.Text
}
