// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package setting

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	IsArchived  pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type GroupRole struct {
	ID          uuid.UUID
	Role        pgtype.Text
	AccessLevel string
}

type Membership struct {
	UserID    uuid.UUID
	GroupID   uuid.UUID
	RoleID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PublicKey struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	PublicKey string
}

type Setting struct {
	UserID        uuid.UUID
	Username      string
	LinuxUsername pgtype.Text
}
