// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	grouprole "clustron-backend/internal/grouprole"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GroupRoleStore is an autogenerated mock type for the GroupRoleStore type
type GroupRoleStore struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *GroupRoleStore) GetByID(ctx context.Context, id uuid.UUID) (grouprole.GroupRole, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 grouprole.GroupRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (grouprole.GroupRole, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) grouprole.GroupRole); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(grouprole.GroupRole)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUser provides a mock function with given fields: ctx, userID, groupID
func (_m *GroupRoleStore) GetByUser(ctx context.Context, userID uuid.UUID, groupID uuid.UUID) (grouprole.GroupRole, error) {
	ret := _m.Called(ctx, userID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 grouprole.GroupRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (grouprole.GroupRole, error)); ok {
		return rf(ctx, userID, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) grouprole.GroupRole); ok {
		r0 = rf(ctx, userID, groupID)
	} else {
		r0 = ret.Get(0).(grouprole.GroupRole)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGroupRoleStore creates a new instance of GroupRoleStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupRoleStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupRoleStore {
	mock := &GroupRoleStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
