// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	membership "clustron-backend/internal/membership"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, userId, groupId, memberIdentifier, role
func (_m *Store) Add(ctx context.Context, userId uuid.UUID, groupId uuid.UUID, memberIdentifier string, role uuid.UUID) (membership.JoinResult, error) {
	ret := _m.Called(ctx, userId, groupId, memberIdentifier, role)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 membership.JoinResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, uuid.UUID) (membership.JoinResult, error)); ok {
		return rf(ctx, userId, groupId, memberIdentifier, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, uuid.UUID) membership.JoinResult); ok {
		r0 = rf(ctx, userId, groupId, memberIdentifier, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(membership.JoinResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = rf(ctx, userId, groupId, memberIdentifier, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByGroupID provides a mock function with given fields: ctx, groupID
func (_m *Store) CountByGroupID(ctx context.Context, groupID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for CountByGroupID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, groupID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWithPaged provides a mock function with given fields: ctx, groupID, page, size, sort, sortBy
func (_m *Store) ListWithPaged(ctx context.Context, groupID uuid.UUID, page int, size int, sort string, sortBy string) ([]membership.Response, error) {
	ret := _m.Called(ctx, groupID, page, size, sort, sortBy)

	if len(ret) == 0 {
		panic("no return value specified for ListWithPaged")
	}

	var r0 []membership.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, string, string) ([]membership.Response, error)); ok {
		return rf(ctx, groupID, page, size, sort, sortBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, string, string) []membership.Response); ok {
		r0 = rf(ctx, groupID, page, size, sort, sortBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]membership.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int, string, string) error); ok {
		r1 = rf(ctx, groupID, page, size, sort, sortBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: ctx, groupID, userID
func (_m *Store) Remove(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, groupID, userID, role
func (_m *Store) Update(ctx context.Context, groupID uuid.UUID, userID uuid.UUID, role uuid.UUID) (membership.MemberResponse, error) {
	ret := _m.Called(ctx, groupID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 membership.MemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (membership.MemberResponse, error)); ok {
		return rf(ctx, groupID, userID, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) membership.MemberResponse); ok {
		r0 = rf(ctx, groupID, userID, role)
	} else {
		r0 = ret.Get(0).(membership.MemberResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID, userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
