// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package membership

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countByGroupID = `-- name: CountByGroupID :one
SELECT COUNT(*) FROM memberships
WHERE group_id = $1
`

func (q *Queries) CountByGroupID(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countByGroupID, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingByGroupID = `-- name: CountPendingByGroupID :one
SELECT COUNT(*) FROM pending_memberships
WHERE group_id = $1
`

func (q *Queries) CountPendingByGroupID(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingByGroupID, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrUpdate = `-- name: CreateOrUpdate :one
INSERT INTO memberships (group_id, user_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, group_id) DO UPDATE SET role_id = EXCLUDED.role_id
RETURNING user_id, group_id, role_id, created_at, updated_at
`

type CreateOrUpdateParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
	RoleID  uuid.UUID
}

func (q *Queries) CreateOrUpdate(ctx context.Context, arg CreateOrUpdateParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createOrUpdate, arg.GroupID, arg.UserID, arg.RoleID)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrUpdatePending = `-- name: CreateOrUpdatePending :one
INSERT INTO pending_memberships (user_identifier, group_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_identifier, group_id) DO UPDATE SET role_id = EXCLUDED.role_id
RETURNING id, user_identifier, group_id, role_id, created_at, updated_at
`

type CreateOrUpdatePendingParams struct {
	UserIdentifier string
	GroupID        uuid.UUID
	RoleID         uuid.UUID
}

func (q *Queries) CreateOrUpdatePending(ctx context.Context, arg CreateOrUpdatePendingParams) (PendingMembership, error) {
	row := q.db.QueryRow(ctx, createOrUpdatePending, arg.UserIdentifier, arg.GroupID, arg.RoleID)
	var i PendingMembership
	err := row.Scan(
		&i.ID,
		&i.UserIdentifier,
		&i.GroupID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM memberships
WHERE group_id = $1 AND user_id = $2
`

type DeleteParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) Delete(ctx context.Context, arg DeleteParams) error {
	_, err := q.db.Exec(ctx, delete, arg.GroupID, arg.UserID)
	return err
}

const deletePendingByID = `-- name: DeletePendingByID :exec
DELETE FROM pending_memberships
WHERE id = $1
`

func (q *Queries) DeletePendingByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingByID, id)
	return err
}

const existsByID = `-- name: ExistsByID :one
SELECT EXISTS (
    SELECT 1
    FROM memberships
    WHERE group_id = $1 AND user_id = $2
) AS exists
`

type ExistsByIDParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) ExistsByID(ctx context.Context, arg ExistsByIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsByID, arg.GroupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsByIdentifier = `-- name: ExistsByIdentifier :one
SELECT EXISTS (
    SELECT 1
    FROM memberships AS m
    JOIN users AS u ON u.id = m.user_id
    WHERE group_id = $1 AND (u.student_id = $2 OR u.email = $2)
)
`

type ExistsByIdentifierParams struct {
	GroupID   uuid.UUID
	StudentID pgtype.Text
}

func (q *Queries) ExistsByIdentifier(ctx context.Context, arg ExistsByIdentifierParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsByIdentifier, arg.GroupID, arg.StudentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsPendingByIdentifier = `-- name: ExistsPendingByIdentifier :one
SELECT EXISTS (
    SELECT 1
    FROM pending_memberships
    WHERE group_id = $1 AND user_identifier = $2
) AS exists
`

type ExistsPendingByIdentifierParams struct {
	GroupID        uuid.UUID
	UserIdentifier string
}

func (q *Queries) ExistsPendingByIdentifier(ctx context.Context, arg ExistsPendingByIdentifierParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsPendingByIdentifier, arg.GroupID, arg.UserIdentifier)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getByUser = `-- name: GetByUser :one
SELECT
    m.user_id,
    m.group_id,
    m.role_id,
    gr.role,
    gr.access_level
FROM
    memberships AS m
        JOIN
    group_role AS gr ON gr.id = m.role_id
WHERE
    user_id = $1 AND group_id = $2
`

type GetByUserParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

type GetByUserRow struct {
	UserID      uuid.UUID
	GroupID     uuid.UUID
	RoleID      uuid.UUID
	Role        string
	AccessLevel string
}

func (q *Queries) GetByUser(ctx context.Context, arg GetByUserParams) (GetByUserRow, error) {
	row := q.db.QueryRow(ctx, getByUser, arg.UserID, arg.GroupID)
	var i GetByUserRow
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.RoleID,
		&i.Role,
		&i.AccessLevel,
	)
	return i, err
}

const getPendingByID = `-- name: GetPendingByID :one
SELECT
    pm.id,
    pm.user_identifier,
    pm.group_id,
    pm.role_id,
    gr.role,
    gr.access_level
FROM pending_memberships AS pm
JOIN group_role AS gr ON gr.id = pm.role_id
WHERE pm.id = $1
`

type GetPendingByIDRow struct {
	ID             uuid.UUID
	UserIdentifier string
	GroupID        uuid.UUID
	RoleID         uuid.UUID
	Role           string
	AccessLevel    string
}

func (q *Queries) GetPendingByID(ctx context.Context, id uuid.UUID) (GetPendingByIDRow, error) {
	row := q.db.QueryRow(ctx, getPendingByID, id)
	var i GetPendingByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserIdentifier,
		&i.GroupID,
		&i.RoleID,
		&i.Role,
		&i.AccessLevel,
	)
	return i, err
}

const getPendingByIdentifier = `-- name: GetPendingByIdentifier :one
SELECT id, user_identifier, group_id, role_id, created_at, updated_at
FROM pending_memberships
WHERE group_id = $1 AND user_identifier = $2
`

type GetPendingByIdentifierParams struct {
	GroupID        uuid.UUID
	UserIdentifier string
}

func (q *Queries) GetPendingByIdentifier(ctx context.Context, arg GetPendingByIdentifierParams) (PendingMembership, error) {
	row := q.db.QueryRow(ctx, getPendingByIdentifier, arg.GroupID, arg.UserIdentifier)
	var i PendingMembership
	err := row.Scan(
		&i.ID,
		&i.UserIdentifier,
		&i.GroupID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingByUserIdentifier = `-- name: GetPendingByUserIdentifier :many
SELECT
    pm.id,
    pm.user_identifier,
    pm.group_id,
    pm.role_id,
    gr.role,
    gr.access_level
FROM pending_memberships AS pm
JOIN group_role AS gr ON gr.id = pm.role_id
WHERE pm.user_identifier = $1 OR pm.user_identifier = $2
`

type GetPendingByUserIdentifierParams struct {
	Email     string
	StudentID string
}

type GetPendingByUserIdentifierRow struct {
	ID             uuid.UUID
	UserIdentifier string
	GroupID        uuid.UUID
	RoleID         uuid.UUID
	Role           string
	AccessLevel    string
}

func (q *Queries) GetPendingByUserIdentifier(ctx context.Context, arg GetPendingByUserIdentifierParams) ([]GetPendingByUserIdentifierRow, error) {
	rows, err := q.db.Query(ctx, getPendingByUserIdentifier, arg.Email, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingByUserIdentifierRow
	for rows.Next() {
		var i GetPendingByUserIdentifierRow
		if err := rows.Scan(
			&i.ID,
			&i.UserIdentifier,
			&i.GroupID,
			&i.RoleID,
			&i.Role,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAscPaged = `-- name: ListAscPaged :many
SELECT
    m.group_id,
    m.user_id,
    s.full_name,
    u.email,
    u.student_id,
    m.role_id,
    gr.role,
    gr.access_level
FROM memberships AS m
JOIN group_role AS gr ON gr.id = m.role_id
JOIN users AS u ON u.id = m.user_id
JOIN settings AS s ON s.user_id = u.id
WHERE group_id = $1
ORDER BY $2::text ASC
LIMIT $4 OFFSET $3
`

type ListAscPagedParams struct {
	GroupID uuid.UUID
	Sortby  string
	Skip    int32
	Size    int32
}

type ListAscPagedRow struct {
	GroupID     uuid.UUID
	UserID      uuid.UUID
	FullName    pgtype.Text
	Email       string
	StudentID   pgtype.Text
	RoleID      uuid.UUID
	Role        string
	AccessLevel string
}

func (q *Queries) ListAscPaged(ctx context.Context, arg ListAscPagedParams) ([]ListAscPagedRow, error) {
	rows, err := q.db.Query(ctx, listAscPaged,
		arg.GroupID,
		arg.Sortby,
		arg.Skip,
		arg.Size,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAscPagedRow
	for rows.Next() {
		var i ListAscPagedRow
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.FullName,
			&i.Email,
			&i.StudentID,
			&i.RoleID,
			&i.Role,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDescPaged = `-- name: ListDescPaged :many
SELECT
    m.group_id,
    m.user_id,
    s.full_name,
    u.email,
    u.student_id,
    m.role_id,
    gr.role,
    gr.access_level
FROM memberships AS m
JOIN group_role AS gr ON gr.id = m.role_id
JOIN users AS u ON u.id = m.user_id
JOIN settings AS s ON s.user_id = u.id
WHERE group_id = $1
ORDER BY $2::text DESC
LIMIT $4 OFFSET $3
`

type ListDescPagedParams struct {
	GroupID uuid.UUID
	Sortby  string
	Skip    int32
	Size    int32
}

type ListDescPagedRow struct {
	GroupID     uuid.UUID
	UserID      uuid.UUID
	FullName    pgtype.Text
	Email       string
	StudentID   pgtype.Text
	RoleID      uuid.UUID
	Role        string
	AccessLevel string
}

func (q *Queries) ListDescPaged(ctx context.Context, arg ListDescPagedParams) ([]ListDescPagedRow, error) {
	rows, err := q.db.Query(ctx, listDescPaged,
		arg.GroupID,
		arg.Sortby,
		arg.Skip,
		arg.Size,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDescPagedRow
	for rows.Next() {
		var i ListDescPagedRow
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.FullName,
			&i.Email,
			&i.StudentID,
			&i.RoleID,
			&i.Role,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMembersAscPaged = `-- name: ListPendingMembersAscPaged :many
SELECT
    pm.id,
    pm.user_identifier,
    pm.group_id,
    pm.role_id,
    gr.role,
    gr.access_level
FROM pending_memberships AS pm
JOIN group_role AS gr ON gr.id = pm.role_id
WHERE pm.group_id = $1
ORDER BY $2::text ASC
LIMIT $4 OFFSET $3
`

type ListPendingMembersAscPagedParams struct {
	GroupID uuid.UUID
	Sortby  string
	Skip    int32
	Size    int32
}

type ListPendingMembersAscPagedRow struct {
	ID             uuid.UUID
	UserIdentifier string
	GroupID        uuid.UUID
	RoleID         uuid.UUID
	Role           string
	AccessLevel    string
}

func (q *Queries) ListPendingMembersAscPaged(ctx context.Context, arg ListPendingMembersAscPagedParams) ([]ListPendingMembersAscPagedRow, error) {
	rows, err := q.db.Query(ctx, listPendingMembersAscPaged,
		arg.GroupID,
		arg.Sortby,
		arg.Skip,
		arg.Size,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingMembersAscPagedRow
	for rows.Next() {
		var i ListPendingMembersAscPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserIdentifier,
			&i.GroupID,
			&i.RoleID,
			&i.Role,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMembersDescPaged = `-- name: ListPendingMembersDescPaged :many
SELECT
    pm.id,
    pm.user_identifier,
    pm.group_id,
    pm.role_id,
    gr.role,
    gr.access_level
FROM pending_memberships AS pm
JOIN group_role AS gr ON gr.id = pm.role_id
WHERE pm.group_id = $1
ORDER BY $2::text DESC
LIMIT $4 OFFSET $3
`

type ListPendingMembersDescPagedParams struct {
	GroupID uuid.UUID
	Sortby  string
	Skip    int32
	Size    int32
}

type ListPendingMembersDescPagedRow struct {
	ID             uuid.UUID
	UserIdentifier string
	GroupID        uuid.UUID
	RoleID         uuid.UUID
	Role           string
	AccessLevel    string
}

func (q *Queries) ListPendingMembersDescPaged(ctx context.Context, arg ListPendingMembersDescPagedParams) ([]ListPendingMembersDescPagedRow, error) {
	rows, err := q.db.Query(ctx, listPendingMembersDescPaged,
		arg.GroupID,
		arg.Sortby,
		arg.Skip,
		arg.Size,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingMembersDescPagedRow
	for rows.Next() {
		var i ListPendingMembersDescPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserIdentifier,
			&i.GroupID,
			&i.RoleID,
			&i.Role,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePending = `-- name: UpdatePending :one
UPDATE pending_memberships
SET role_id = $1
WHERE group_id = $2 AND user_identifier = $3
RETURNING id, user_identifier, group_id, role_id, created_at, updated_at
`

type UpdatePendingParams struct {
	RoleID         uuid.UUID
	GroupID        uuid.UUID
	UserIdentifier string
}

func (q *Queries) UpdatePending(ctx context.Context, arg UpdatePendingParams) (PendingMembership, error) {
	row := q.db.QueryRow(ctx, updatePending, arg.RoleID, arg.GroupID, arg.UserIdentifier)
	var i PendingMembership
	err := row.Scan(
		&i.ID,
		&i.UserIdentifier,
		&i.GroupID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePendingByID = `-- name: UpdatePendingByID :one
UPDATE pending_memberships
SET role_id = $1
WHERE id = $2
RETURNING id, user_identifier, group_id, role_id, created_at, updated_at
`

type UpdatePendingByIDParams struct {
	RoleID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) UpdatePendingByID(ctx context.Context, arg UpdatePendingByIDParams) (PendingMembership, error) {
	row := q.db.QueryRow(ctx, updatePendingByID, arg.RoleID, arg.ID)
	var i PendingMembership
	err := row.Scan(
		&i.ID,
		&i.UserIdentifier,
		&i.GroupID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE memberships
SET role_id = $1
WHERE group_id = $2 AND user_id = $3
RETURNING user_id, group_id, role_id, created_at, updated_at
`

type UpdateRoleParams struct {
	RoleID  uuid.UUID
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.RoleID, arg.GroupID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
