- name: Install NFS Client
  become: true
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Ensure mount points exist on compute nodes
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /home
    - /opt
    - /etc/slurm

- name: Mount NFS Shares and update /etc/fstab
  become: true
  ansible.posix.mount:
    path: "{{ item }}"
    src: "{{ head_node_ip }}:{{ item }}"
    fstype: nfs
    opts: defaults,_netdev
    state: mounted
  loop:
    - /home
    - /opt
    - /etc/slurm
