// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package group

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	IsArchived  pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type GroupAccessLevel struct {
	Role        string
	AccessLevel string
}

type Membership struct {
	UserID    uuid.UUID
	GroupID   uuid.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
