// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package group

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archive = `-- name: Archive :one
UPDATE groups SET is_archived = TRUE, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, title, description, is_archived, created_at, updated_at
`

func (q *Queries) Archive(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, archive, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAll = `-- name: CountAll :one
SELECT COUNT(*) FROM groups
`

func (q *Queries) CountAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countByUser = `-- name: CountByUser :one
SELECT COUNT(*) FROM memberships WHERE user_id = $1
`

func (q *Queries) CountByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const create = `-- name: Create :one
INSERT INTO groups (title, description) VALUES ($1, $2) RETURNING id, title, description, is_archived, created_at, updated_at
`

type CreateParams struct {
	Title       string
	Description pgtype.Text
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Group, error) {
	row := q.db.QueryRow(ctx, create, arg.Title, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const get = `-- name: Get :one
SELECT id, title, description, is_archived, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccessLevelByRoleID = `-- name: GetAccessLevelByRoleID :one
SELECT access_level FROM group_role WHERE id = $1
`

func (q *Queries) GetAccessLevelByRoleID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAccessLevelByRoleID, id)
	var access_level string
	err := row.Scan(&access_level)
	return access_level, err
}

const getGroupRoleByID = `-- name: GetGroupRoleByID :one
SELECT id, role, access_level FROM group_role WHERE id = $1
`

func (q *Queries) GetGroupRoleByID(ctx context.Context, id uuid.UUID) (GroupRole, error) {
	row := q.db.QueryRow(ctx, getGroupRoleByID, id)
	var i GroupRole
	err := row.Scan(&i.ID, &i.Role, &i.AccessLevel)
	return i, err
}

const getIfMember = `-- name: GetIfMember :one
SELECT g.id, g.title, g.description, g.is_archived, g.created_at, g.updated_at FROM groups AS g JOIN memberships AS m ON m.group_id = g.id WHERE m.user_id = $1 AND m.group_id = $2
`

type GetIfMemberParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) GetIfMember(ctx context.Context, arg GetIfMemberParams) (Group, error) {
	row := q.db.QueryRow(ctx, getIfMember, arg.UserID, arg.GroupID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipsByUser = `-- name: GetMembershipsByUser :one
SELECT
    m.group_id,
    m.role_id,
    gr.role,
    gr.access_level
FROM
    memberships AS m
JOIN
    group_role AS gr ON gr.id = m.role_id
WHERE
    user_id = $1 AND group_id = $2
`

type GetMembershipsByUserParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

type GetMembershipsByUserRow struct {
	GroupID     uuid.UUID
	RoleID      uuid.UUID
	Role        pgtype.Text
	AccessLevel string
}

func (q *Queries) GetMembershipsByUser(ctx context.Context, arg GetMembershipsByUserParams) (GetMembershipsByUserRow, error) {
	row := q.db.QueryRow(ctx, getMembershipsByUser, arg.UserID, arg.GroupID)
	var i GetMembershipsByUserRow
	err := row.Scan(
		&i.GroupID,
		&i.RoleID,
		&i.Role,
		&i.AccessLevel,
	)
	return i, err
}

const getUserGroupRole = `-- name: GetUserGroupRole :one
SELECT gr.id, gr.role, gr.access_level FROM group_role AS gr JOIN memberships AS m ON m.role_id = gr.id WHERE m.user_id = $1 AND m.group_id = $2
`

type GetUserGroupRoleParams struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) GetUserGroupRole(ctx context.Context, arg GetUserGroupRoleParams) (GroupRole, error) {
	row := q.db.QueryRow(ctx, getUserGroupRole, arg.UserID, arg.GroupID)
	var i GroupRole
	err := row.Scan(&i.ID, &i.Role, &i.AccessLevel)
	return i, err
}

const listAscPaged = `-- name: ListAscPaged :many
SELECT id, title, description, is_archived, created_at, updated_at FROM groups ORDER BY $1::text ASC LIMIT $3 OFFSET $2
`

type ListAscPagedParams struct {
	Sortby string
	Page   int32
	Size   int32
}

func (q *Queries) ListAscPaged(ctx context.Context, arg ListAscPagedParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, listAscPaged, arg.Sortby, arg.Page, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByUserAscPaged = `-- name: ListByUserAscPaged :many
SELECT
    g.id, g.title, g.description, g.is_archived, g.created_at, g.updated_at,
    gr.id, gr.role, gr.access_level
FROM
    groups AS g
JOIN
    memberships AS m ON m.group_id = g.id
JOIN
    group_role AS gr ON gr.id = m.role_id
WHERE
    m.user_id = $1
ORDER BY
    $2::text ASC LIMIT $4 OFFSET $3
`

type ListByUserAscPagedParams struct {
	UserID uuid.UUID
	Sortby string
	Page   int32
	Size   int32
}

type ListByUserAscPagedRow struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	IsArchived  pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ID_2        uuid.UUID
	Role        pgtype.Text
	AccessLevel string
}

func (q *Queries) ListByUserAscPaged(ctx context.Context, arg ListByUserAscPagedParams) ([]ListByUserAscPagedRow, error) {
	rows, err := q.db.Query(ctx, listByUserAscPaged,
		arg.UserID,
		arg.Sortby,
		arg.Page,
		arg.Size,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListByUserAscPagedRow
	for rows.Next() {
		var i ListByUserAscPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.Role,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByUserDescPaged = `-- name: ListByUserDescPaged :many
SELECT
    g.id, g.title, g.description, g.is_archived, g.created_at, g.updated_at,
    gr.id, gr.role, gr.access_level
FROM
    groups AS g
JOIN
    memberships AS m ON m.group_id = g.id
JOIN
    group_role AS gr ON gr.id = m.role_id
WHERE
    m.user_id = $1
ORDER BY
    $2::text DESC LIMIT $4 OFFSET $3
`

type ListByUserDescPagedParams struct {
	UserID uuid.UUID
	Sortby string
	Page   int32
	Size   int32
}

type ListByUserDescPagedRow struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	IsArchived  pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ID_2        uuid.UUID
	Role        pgtype.Text
	AccessLevel string
}

func (q *Queries) ListByUserDescPaged(ctx context.Context, arg ListByUserDescPagedParams) ([]ListByUserDescPagedRow, error) {
	rows, err := q.db.Query(ctx, listByUserDescPaged,
		arg.UserID,
		arg.Sortby,
		arg.Page,
		arg.Size,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListByUserDescPagedRow
	for rows.Next() {
		var i ListByUserDescPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.Role,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDescPaged = `-- name: ListDescPaged :many
SELECT id, title, description, is_archived, created_at, updated_at FROM groups ORDER BY $1::text DESC LIMIT $3 OFFSET $2
`

type ListDescPagedParams struct {
	Sortby string
	Page   int32
	Size   int32
}

func (q *Queries) ListDescPaged(ctx context.Context, arg ListDescPagedParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, listDescPaged, arg.Sortby, arg.Page, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT
    m.group_id,
    m.role_id,
    gr.role,
    gr.access_level
FROM
    memberships AS m
JOIN
    group_role AS gr ON gr.id = m.role_id
WHERE
    user_id = $1
`

type ListMembershipsByUserRow struct {
	GroupID     uuid.UUID
	RoleID      uuid.UUID
	Role        pgtype.Text
	AccessLevel string
}

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsByUserRow
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.GroupID,
			&i.RoleID,
			&i.Role,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchive = `-- name: Unarchive :one
UPDATE groups SET is_archived = FALSE, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, title, description, is_archived, created_at, updated_at
`

func (q *Queries) Unarchive(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, unarchive, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const update = `-- name: Update :one
UPDATE groups SET title = $2, description = $3, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, title, description, is_archived, created_at, updated_at
`

type UpdateParams struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Group, error) {
	row := q.db.QueryRow(ctx, update, arg.ID, arg.Title, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
