- name: Install NFS Server
  become: true
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present

- name: Ensure exported directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /home
    - /opt
    - /etc/slurm

- name: Configure NFS exports
  become: true
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'

- name: Reload NFS
  become: true
  ansible.builtin.command: exportfs -ra
  changed_when: true
