- name: Create slurm group
  become: true
  group:
    name: slurm
    gid: 1002

- name: Create slurm user
  become: true
  user:
    name: slurm
    uid: 1002
    group: slurm
    home: /var/lib/slurm
    create_home: yes
    shell: /bin/bash

- name: Create local Slurm directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'
  loop:
    - /var/spool/slurm
    - /var/spool/slurm/d
    - /var/log/slurm

- name: Install Compute packages
  become: true
  apt:
    deb: "/opt/clustron_share/{{ env_dir }}/{{ item }}"
  loop:
    - "slurm-smd_{{ slurm_version }}_amd64.deb"
    - "slurm-smd-client_{{ slurm_version }}_amd64.deb"
    - "slurm-smd-slurmd_{{ slurm_version }}_amd64.deb"

- name: Ensure slurmd is running and enabled
  become: true
  service:
    name: slurmd
    state: started
    enabled: yes
