- name: Install chrony
  become: true
  apt:
    name: chrony
    state: present
    update_cache: yes

- name: Allow compute nodes to sync time
  become: true
  lineinfile:
    path: /etc/chrony/chrony.conf
    line: "allow all"
    state: present
  notify: Restart Chrony

- name: Ensure chrony service is enabled and started
  become: yes
  service:
    name: chrony
    state: started
    enabled: yes

- name: Add iptables rule for compute nodes (UDP 123)
  become: yes
  shell: |
    iptables -C INPUT -p udp -s {{ hostvars[item].ansible_default_ipv4.address }} --dport 123 -j ACCEPT || \
    iptables -I INPUT -p udp -s {{ hostvars[item].ansible_default_ipv4.address }} --dport 123 -j ACCEPT
  loop: "{{ groups['compute_nodes'] }}"
  register: iptables_result
  changed_when: "'iptables -I' in iptables_result.cmd"

- name: Install iptables-persistent
  become: yes
  apt:
    name: iptables-persistent
    state: present

- name: Save iptables rules
  become: true
  shell: netfilter-persistent save
