all:
    vars:
        head_node_ip: ansible_cpu_1
        slurm_version: 25.11.4-1
    children:
        head_nodes:
            hosts:
                ansible-cpu2:
                    ansible_host: ansible_cpu_1
                    ansible_user: ubuntu
                ansible-head:
                    ansible_host: ansible_head
                    ansible_user: ubuntu
