- name: Gather facts from all nodes
  hosts: all
  gather_facts: true

- name: Setup Header Node
  hosts: head_nodes
  roles:
    - common
    - ntp_server
    - nfs_server
    - ldap_server
    - slurm_builder
    - slurm_controller

- name: Set Up Compute Nodes
  hosts: compute_nodes
  roles:
    - common
    - ntp_client
    - role: nfs_client
      when: (mount_nfs_home | default(true) | bool) or (enable_slurm | default(true) | bool)
    - ldap_client
    - role: slurm_builder
      when: enable_slurm | default(true) | bool
    - role: slurm_compute
      when: enable_slurm | default(true) | bool
