// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MembershipService is an autogenerated mock type for the MembershipService type
type MembershipService struct {
	mock.Mock
}

// ProcessPendingMemberships provides a mock function with given fields: ctx, userID, email, studentID
func (_m *MembershipService) ProcessPendingMemberships(ctx context.Context, userID uuid.UUID, email string, studentID string) error {
	ret := _m.Called(ctx, userID, email, studentID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPendingMemberships")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = rf(ctx, userID, email, studentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
